language: ruby
cache: bundler
sudo: false
rvm:
- 1.9.3
services:
- mongodb
- redis
script:
  - bundle exec rake
bundler_args: --without=development
env:
  global:
  - GOVUK_APP_DOMAIN=dev.gov.uk
  - RUBYOPT="-rpsych"
  - FACTER_govuk_platform=test